# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

<<<<<<< HEAD
title: Madhav's CS Blog
description: All my activities and experiences in one place-mostly ML stuff.
github_username: PseudoCodeNerd
# you can comment the below line out if your repo name is not different than your baseurl
github_repo: "blog"

# OPTIONAL: override baseurl and url if using a custom domain
# Note: leave out the trailing / from this value. 
url: "https://PseudoCodeNerd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
=======
title: fastpages
description: An easy to use blogging platform with support for Jupyter Notebooks.
github_username: fastai
# you can comment the below line out if your repo name is not different than your baseurl
github_repo: "fastpages"

# OPTIONAL: override baseurl and url if using a custom domain
# Note: leave out the trailing / from this value. 
url: "https://fastpages.fast.ai" # the base hostname & protocol for your site, e.g. http://example.com
>>>>>>> template/master

###########################################################
#########  Special Instructions for baseurl ###############
#
#### Scenario One: If you do not have a Custom Domain #####
#    -  if you are not using a custom domain, the baseurl *must* be set to your repo name
# 
####  Scenario Two: If you have a Custom Domain #####
# 1. If your domain does NOT have a subpath, this leave this value as ""
# 2. If your domain does have a subpath, you must preceed the value with a / and NOT have a / at the end.  
#      For example: 
#           "" is valid
#           "/blog"        is valid
#            "/blog/site/" is invalid  ( / at the end)
#            "/blog/site"  is valid
#            "blog/site"   is invalid  ( because doesn't begin with a /)
#
# 3. You must replace the parameter `baseurl` in _action_files/settings.ini with the same value as you set here but WITHOUT QUOTES.
#
<<<<<<< HEAD
baseurl: "/blog" # the subpath of your site, e.g. "/blog".
=======
baseurl: "" # the subpath of your site, e.g. "/blog".
>>>>>>> template/master

# Github and twitter are optional:
minima:
  social_links:
<<<<<<< HEAD
    twitter: sharmadhav03
    github: pseudocodenerd

# Set this to true to get LaTeX math equation support
use_math: true
=======
    twitter: fastdotai
    github: fastai

# Set this to true to get LaTeX math equation support
use_math: 
>>>>>>> template/master

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true

# Set this to true to display image previews on home page, if they exist
<<<<<<< HEAD
show_image: true
=======
show_image: false

# Set this to true to turn on annotations with hypothes.is (https://web.hypothes.is/)
annotations: false
>>>>>>> template/master

# Set this to true to display tags on each post
show_tags: true

# Add your Google Analytics ID here if you have one and want to use it
<<<<<<< HEAD
google_analytics:
=======
google_analytics: UA-57531313-5
>>>>>>> template/master

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

<<<<<<< HEAD
=======
# This specifies what badges are turned on by default for notebook posts.
default_badges:
  github: true
  binder: true
  colab: true

# Escape HTML in post descriptions
html_escape:
  description: false

>>>>>>> template/master
# Everything below here should be left alone. Modifications may break fastpages
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
<<<<<<< HEAD

# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 10
=======
  - jekyll-sitemap
  - jemoji

# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 15
>>>>>>> template/master
paginate_path: /page:num/

remote_theme: jekyll/minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
<<<<<<< HEAD
=======

# to limit size of xml as it can grow quite large.
feed:
  posts_limit: 5 #default posts_limit: 10
  excerpt_only: true
  
exclude:
  - settings.ini
>>>>>>> template/master
